### ISSUE TITLE
Funker ikke

### ISSUE THREAD

**Issue by erlendb** [bjornksa/TTK4145#1]

**Comment by bjornksa** [comment]
Sannsynligvis en feil med Windows eller VSCode. Fins en bug i Windows 10 som gjør at hvis man skriver kode på windows så fungerer den ikke

Kan sannsynligvis fikses hvis vi bruker et språk som kan kjøre C-kode (med parameter)

**Comment by bjornksa** [comment]
![image](https://user-images.githubusercontent.com/47418250/73476972-aa061400-4393-11ea-8113-337be01259b5.png)


Ser ut som Atom kan være synderen

**Comment by erlendb** [comment]
Fikset denne bugen med Atom.
